spring.application.name=CLIP



# JPA
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Database
server.port=8080
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=INFO
# JWT Configs (JwtUtil)
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.time=${JWT_EXPIRATION_TIME}


logging.level.org.springframework.security=DEBUG

# Python API
python.api.base-url=${PYTHON_API_URL}
